Repository yuenherny/TermDepositSolutionChecker-WebApp, pull requests merged in 2021-06, with the labels that each got.

#1 app v1 complete
  .gitignore
  requirements.txt
  test/csvtest-100.csv
  webapp/__init__.py
  webapp/__pycache__/verify.cpython-38.pyc
  webapp/app.py
  webapp/verify.py
Labels: enhancement

#3 Update readme
  README.md
  metadata/clickhere.png
  webapp/streamlit_app.py
Labels: documentation

#4 update license boilerplate
  webapp/streamlit_app.py
  webapp/verify.py
Labels: license

#5 remove testfile, update gitignore
  .gitignore
  test/csvtest-100.csv
Labels: test

#6 update secrets mgt in readme
  README.md
Labels: documentation

#7 fix typo
  README.md
  webapp/streamlit_app.py
  webapp/verify.py
Labels: documentation
